export const CATEGORY_NAMES: Record<string, string> = {
  core: 'Core',
  places: 'Places',
  ventures: 'Ventures',
  business: 'Business',
  philosophy: 'Philosophy',
  building: 'Building',
  design: 'Design',
  language: 'Language',
  culture: 'Culture',
  youtube: 'YouTube',
  curiosity: 'Curiosity',
  reading: 'Reading',
  tools: 'Tools',
  tech: 'Tech',
  habits: 'Habits',
  money: 'Money',
  communication: 'Communication',
  frictions: 'Frictions',
  meta: 'Meta',
};

export const CATEGORY_ORDER = [
  'core', 'places', 'ventures', 'business',
  'philosophy', 'building', 'design',
  'language', 'culture', 'youtube',
  'curiosity', 'reading',
  'tools', 'tech',
  'habits', 'money', 'communication', 'frictions',
  'meta',
];

export const CATEGORY_COLORS: Record<string, string> = {
  core: '#3f5f8f',
  places: '#557a62',
  ventures: '#9c5b3f',
  business: '#7a4f3d',
  philosophy: '#5d4d7a',
  building: '#8a6236',
  design: '#2f6f73',
  language: '#47746d',
  culture: '#8a4f6b',
  youtube: '#b14a43',
  curiosity: '#2e6485',
  reading: '#6b6775',
  tools: '#4d6b73',
  tech: '#3c5b73',
  habits: '#5b7b54',
  money: '#8b7337',
  communication: '#596979',
  frictions: '#7b4d4d',
  meta: '#746b61',
};

export const SECTION_ORDER = [
  'navigation',
  'identity',
  'people',
  'ventures',
  'concepts',
  'skills',
  'media',
  'life',
  'events',
  'timeline',
  'curiosity',
] as const;

export type SectionKey = (typeof SECTION_ORDER)[number];

export const SECTION_NAMES: Record<SectionKey, string> = {
  navigation: 'Navigation',
  identity: 'Identity',
  people: 'People',
  ventures: 'Ventures & Projects',
  concepts: 'Concepts & Philosophy',
  skills: 'Skills & Tools',
  media: 'Media',
  life: 'Life & Personal',
  events: 'Events & Experiences',
  timeline: 'Timeline',
  curiosity: 'Curiosity',
};

export const SECTION_DESCRIPTIONS: Record<SectionKey, string> = {
  navigation: 'Entry points, orientation pages, and the chapters that explain how to move through the archive.',
  identity: 'The inner spine: self-concepts, recurring traits, motives, and the language I use to describe my own shape.',
  people: 'The individuals who matter here, whether through family, influence, admiration, collaboration, or memory.',
  ventures: 'The businesses, experiments, and long-building undertakings where thought turns into work and direction becomes concrete.',
  concepts: 'The frameworks, principles, beliefs, frictions, and philosophical positions that quietly govern the rest of the world.',
  skills: 'The crafts, capabilities, technologies, and working instruments that let ideas become output.',
  media: 'The books, shows, channels, essays, and cultural inputs that sharpen taste, language, and perspective.',
  life: 'Place, routine, language, health, memory, and the private conditions underneath the visible work.',
  events: 'Specific lived moments and experiences that changed the texture of how I think, work, or understand myself.',
  timeline: 'A chronological sense of phases, transitions, and eras, so the archive can be read across time as well as theme.',
  curiosity: 'Open questions, recurring obsessions, and the parts of the world that keep pulling my attention forward.',
};

export const SECTION_COLORS: Record<SectionKey, string> = {
  navigation: '#8c7b66',
  identity: '#3f5f8f',
  people: '#6e7c4a',
  ventures: '#9c5b3f',
  concepts: '#5d4d7a',
  skills: '#2f6f73',
  media: '#8a4f6b',
  life: '#4d7b5c',
  events: '#b0722a',
  timeline: '#52667a',
  curiosity: '#2e6485',
};

export const SECTION_CATEGORY_MAP: Record<SectionKey, string[]> = {
  navigation: ['meta'],
  identity: ['core'],
  people: [],
  ventures: ['ventures'],
  concepts: ['business', 'building', 'philosophy', 'money', 'communication', 'frictions'],
  skills: ['design', 'language', 'tools', 'tech'],
  media: ['culture', 'youtube', 'reading'],
  life: ['places', 'habits'],
  events: [],
  timeline: [],
  curiosity: ['curiosity'],
};

export const SECTION_PRIORITY_SLUGS: Partial<Record<SectionKey, string[]>> = {
  navigation: [
    'meta/start-here',
    'meta/map-of-the-wiki',
    'meta/timeline',
    'meta/formative-experiences',
    'meta/hendrixpedia',
    'meta/how-this-wiki-works',
    'meta/raw-context',
    'meta/for-the-chatbot',
  ],
  identity: [
    'core/hendrix',
    'core/being-a-builder',
    'core/identity',
    'core/what-lasts',
    'core/close-to-the-work',
    'core/range',
    'core/responsibility-for-outcomes',
    'core/learning-across-surfaces',
    'core/the-cost-of-range',
    'core/becoming',
  ],
  people: ['core/hendrix', 'core/hendrix-huynh', 'philosophy/nietzsche', 'philosophy/camus'],
  ventures: ['ventures/duodode', 'ventures/digital-agency', 'ventures/agency-building', 'ventures/ai-automation'],
  concepts: ['philosophy/philosophy', 'building/build-and-ship', 'business/leverage', 'money/money'],
  skills: ['design/design-philosophy', 'language/english', 'tools/codex', 'tech/javascript'],
  media: ['reading/reading-as-self-reconstruction', 'culture/mad-men', 'youtube/the-futur', 'reading/essays'],
  life: ['places/dubai', 'places/vietnam', 'habits/running', 'habits/reading-habit'],
  events: ['meta/formative-experiences'],
  timeline: ['meta/timeline'],
  curiosity: ['curiosity/space', 'curiosity/science-fiction', 'curiosity/wonder'],
};
