export const CATEGORY_NAMES: Record<string, string> = {
  core: 'Core',
  people: 'People',
  places: 'Places',
  ventures: 'Ventures',
  business: 'Business',
  philosophy: 'Philosophy',
  building: 'Building',
  design: 'Design',
  language: 'Language',
  culture: 'Culture',
  youtube: 'YouTube',
  curiosity: 'Curiosity',
  reading: 'Reading',
  books: 'Books',
  music: 'Music',
  events: 'Events',
  tools: 'Tools',
  tech: 'Tech',
  habits: 'Habits',
  money: 'Money',
  communication: 'Communication',
  frictions: 'Frictions',
  meta: 'Meta',
};

export const CATEGORY_ORDER = [
  'core', 'people', 'places', 'ventures', 'business',
  'philosophy', 'building', 'design',
  'language', 'culture', 'youtube',
  'curiosity', 'reading', 'books', 'music', 'events',
  'tools', 'tech',
  'habits', 'money', 'communication', 'frictions',
  'meta',
];

export const CATEGORY_COLORS: Record<string, string> = {
  core: '#3f5f8f',
  people: '#6e7c4a',
  places: '#557a62',
  ventures: '#9c5b3f',
  business: '#7a4f3d',
  philosophy: '#5d4d7a',
  building: '#8a6236',
  design: '#2f6f73',
  language: '#47746d',
  culture: '#8a4f6b',
  youtube: '#b14a43',
  curiosity: '#2e6485',
  reading: '#6b6775',
  books: '#6d665b',
  music: '#8f5870',
  events: '#b0722a',
  tools: '#4d6b73',
  tech: '#3c5b73',
  habits: '#5b7b54',
  money: '#8b7337',
  communication: '#596979',
  frictions: '#7b4d4d',
  meta: '#746b61',
};

export const SECTION_ORDER = [
  'navigation',
  'people',
  'ventures',
  'events',
  'identity',
  'concepts',
  'skills',
  'curiosity',
  'media',
  'music',
  'books',
  'life',
] as const;

export type SectionKey = (typeof SECTION_ORDER)[number] | 'timeline';
export type CuratedSectionEntry = string | { slug: string; title?: string };

export const SECTION_NAMES: Record<SectionKey, string> = {
  navigation: 'Navigation',
  identity: 'Identity',
  people: 'People',
  ventures: 'Ventures & Projects',
  concepts: 'Concepts & Philosophy',
  skills: 'Skills & Tools',
  media: 'Media',
  books: 'Books',
  music: 'Music',
  life: 'Life & Personal',
  events: 'Events & Experiences',
  timeline: 'Timeline',
  curiosity: 'Curiosity',
};

export const SECTION_DESCRIPTIONS: Record<SectionKey, string> = {
  navigation: 'Entry points, orientation pages, and the chapters that explain how to move through the archive.',
  identity: 'The self-description layer: the chapters that answer who I am, what keeps returning in me, and what kind of person I am still becoming.',
  people: 'The individuals who matter here, whether through family, influence, admiration, collaboration, or memory.',
  ventures: 'The businesses, experiments, and long-building undertakings where thought turns into work and direction becomes concrete.',
  concepts: 'The operating system: the principles, frames, and philosophical lines that shape how I think, decide, and build.',
  skills: 'The crafts, capabilities, technologies, and working instruments that let ideas become output.',
  media: 'The shows, channels, essays, and broader cultural inputs that sharpen taste, language, and perspective.',
  books: 'The books, reading habits, and written works that sharpen perspective, imagination, and judgment.',
  music: 'The artists, albums, songs, and musical influences that shape atmosphere, taste, and momentum.',
  life: 'Place, routine, language, health, memory, and the private conditions underneath the visible work.',
  events: 'Specific lived moments and experiences that changed the texture of how I think, work, or understand myself.',
  timeline: 'A chronological sense of phases, transitions, and eras, so the archive can be read across time as well as theme.',
  curiosity: 'Open questions, recurring obsessions, and the parts of the world that keep pulling my attention forward.',
};

export const SECTION_COLORS: Record<SectionKey, string> = {
  navigation: '#8c7b66',
  identity: '#3f5f8f',
  people: '#6e7c4a',
  ventures: '#9c5b3f',
  concepts: '#5d4d7a',
  skills: '#2f6f73',
  media: '#8a4f6b',
  books: '#6d665b',
  music: '#8f5870',
  life: '#4d7b5c',
  events: '#b0722a',
  timeline: '#52667a',
  curiosity: '#2e6485',
};

export const SECTION_CATEGORY_MAP: Record<SectionKey, string[]> = {
  navigation: ['meta'],
  identity: ['core'],
  people: ['people'],
  ventures: ['ventures'],
  concepts: ['business', 'building', 'philosophy', 'money', 'communication', 'frictions'],
  skills: ['design', 'language', 'tools', 'tech'],
  media: ['culture', 'youtube'],
  books: ['reading', 'books'],
  music: ['music'],
  life: ['places', 'habits'],
  events: ['events'],
  timeline: [],
  curiosity: ['curiosity'],
};

export const SECTION_PRIORITY_SLUGS: Partial<Record<SectionKey, string[]>> = {
  navigation: [
    'meta/start-here',
    'meta/map-of-the-wiki',
    'meta/timeline',
    'meta/formative-experiences',
    'meta/hendrixpedia',
    'meta/how-this-wiki-works',
    'meta/raw-context',
    'meta/for-the-chatbot',
  ],
  identity: [
    'core/hendrix',
    'core/being-a-builder',
    'core/what-lasts',
    'core/responsibility-for-outcomes',
    'core/learning-across-surfaces',
    'core/the-cost-of-range',
    'core/becoming',
    'core/competence',
    'core/seriousness',
  ],
  people: [],
  ventures: [
    'ventures/duodode',
    'ventures/hyped-indie',
    'ventures/simplifly',
    'ventures/astro-view',
    'ventures/ecom-stores',
    'ventures/youtube-channel',
  ],
  concepts: [
    'philosophy/philosophy',
    'core/being-a-builder',
    'core/becoming',
    'philosophy/self-overcoming',
    'building/build-and-ship',
    'building/execution-over-talk',
  ],
  skills: ['design/design-philosophy', 'language/english', 'tools/codex', 'tech/javascript'],
  media: ['culture/mad-men', 'youtube/the-futur'],
  books: ['books/recommended-books', 'reading/reading-as-self-reconstruction', 'reading/red-rising', 'reading/essays'],
  music: ['music/music', 'youtube/j-cole'],
  life: ['places/dubai', 'places/vietnam', 'habits/running', 'habits/reading-habit'],
  events: [
    'events/yec-the-connection-2023',
    'events/yec-club-pitch',
    'events/campari-italys-national-day-event',
    'events/the-clash-tournament',
    'events/covid-19-running-habit',
    'events/learning-how-to-code',
    'events/davinci-resolve-crash',
    'events/bai-dinh-summer-retreat',
    'events/solo-trekking',
    'events/dubai-mallathon',
    'events/nevermind-cobuild',
  ],
  timeline: ['meta/timeline'],
  curiosity: ['curiosity/space', 'curiosity/science-fiction', 'curiosity/wonder'],
};

export const SECTION_CURATED_SLUGS: Partial<Record<SectionKey, CuratedSectionEntry[]>> = {
  ventures: [
    'ventures/duodode',
    'ventures/hyped-indie',
    'ventures/simplifly',
    'ventures/astro-view',
    'ventures/ecom-stores',
    'ventures/youtube-channel',
  ],
  identity: [
    'core/hendrix',
    'core/being-a-builder',
    'core/what-lasts',
    'core/responsibility-for-outcomes',
    'core/learning-across-surfaces',
    'core/the-cost-of-range',
    'core/becoming',
    'core/competence',
    'core/seriousness',
  ],
  concepts: [
    'philosophy/philosophy',
    { slug: 'core/being-a-builder', title: 'Builder' },
    'core/becoming',
    'philosophy/self-overcoming',
    'philosophy/hedgehogs-dilemma',
    'building/build-and-ship',
    'building/execution-over-talk',
    'philosophy/small-things-are-not-small',
    'philosophy/making-space',
    'philosophy/reading-and-the-mind',
    'philosophy/language-as-thought',
    'philosophy/we-come-from-stars',
  ],
  skills: [
    'tools/figma',
    'tools/claude-and-codex',
    'tools/vs-code',
    'tech/html-css',
    'tech/javascript',
    'tools/postman-api-testing',
    'tools/rive',
    'tools/davinci-resolve',
    'tools/n8n',
    'tools/next-js',
    'tools/node-js',
    'tools/supabase',
    'tools/vercel',
    'tools/github',
    'language/duolingo',
    'tech/framer-motion',
    'tech/gsap',
    'culture/bartending',
    'business/paid-marketing',
    'communication/public-speaking',
  ],
  events: [
    'events/yec-the-connection-2023',
    'events/yec-club-pitch',
    'events/campari-italys-national-day-event',
    'events/the-clash-tournament',
    'events/covid-19-running-habit',
    'events/learning-how-to-code',
    'events/davinci-resolve-crash',
    'events/bai-dinh-summer-retreat',
    'events/solo-trekking',
    'events/dubai-mallathon',
    'events/nevermind-cobuild',
  ],
};
