export const CATEGORY_NAMES: Record<string, string> = {
  core: 'Core identity',
  places: 'Places',
  ventures: 'Ventures',
  business: 'Business',
  philosophy: 'Philosophy',
  building: 'Building',
  design: 'Design',
  language: 'Languages',
  culture: 'Culture',
  youtube: 'YouTube',
  curiosity: 'Curiosity',
  reading: 'Reading',
  tools: 'Tools',
  tech: 'Tech',
  habits: 'Habits',
  money: 'Money',
  communication: 'Communication',
  frictions: 'Frictions',
  meta: 'Meta',
};

export const CATEGORY_ORDER = [
  'core', 'places', 'ventures', 'business',
  'philosophy', 'building', 'design',
  'language', 'culture', 'youtube',
  'curiosity', 'reading',
  'tools', 'tech',
  'habits', 'money', 'communication', 'frictions',
  'meta',
];

export const CATEGORY_COLORS: Record<string, string> = {
  core: '#3366cc',
  places: '#2aa889',
  ventures: '#b56f3d',
  business: '#c0503a',
  philosophy: '#6a4ba6',
  building: '#d38a00',
  design: '#2e8dd0',
  language: '#4a9c68',
  culture: '#9a3f75',
  youtube: '#cc3333',
  curiosity: '#2b7fa0',
  reading: '#7a7a7a',
  tools: '#445566',
  tech: '#556677',
  habits: '#558b55',
  money: '#967b34',
  communication: '#6a7b8d',
  frictions: '#8a4a4a',
  meta: '#000000',
};
